import "~/styles/globals.css";

import { type Metadata } from "next";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function AuthLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-[#4199ae] to-[#00222a]">
            {children}
        </main>
    );
}
